# GitHub Actions Workflow for Vulkan Labs Website (Static Version)
# File: .github/workflows/deploy.yml

name: Deploy Vulkan Labs Website

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Quality assurance and testing
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (for tools only)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install validation tools
      run: |
        npm install -g htmlhint stylelint eslint
        
    - name: Validate HTML
      run: |
        htmlhint index.html 404.html || echo "HTML validation completed"
        
    - name: Validate CSS
      run: |
        stylelint style.css --config-basedir ./ || echo "CSS validation completed"
        
    - name: Validate JavaScript
      run: |
        eslint script.js --no-eslintrc --env browser,es6 --parserOptions ecmaVersion:2022 || echo "JS validation completed"
        
    - name: Check file structure
      run: |
        echo "Checking required files..."
        ls -la
        echo "✅ Files found:"
        [ -f index.html ] && echo "  - index.html" || echo "  ❌ index.html missing"
        [ -f style.css ] && echo "  - style.css" || echo "  ❌ style.css missing"
        [ -f script.js ] && echo "  - script.js" || echo "  ❌ script.js missing"
        [ -f manifest.json ] && echo "  - manifest.json" || echo "  ⚠️ manifest.json missing (optional)"
        [ -f sw.js ] && echo "  - sw.js" || echo "  ⚠️ sw.js missing (optional)"
        
    - name: Security scan
      run: |
        echo "Running basic security checks..."
        # Check for common security issues
        grep -r "document.write\|eval(" . --include="*.js" --include="*.html" && echo "⚠️ Potential security issues found" || echo "✅ No obvious security issues found"
        
    - name: Performance check
      run: |
        echo "Checking file sizes..."
        find . -name "*.js" -o -name "*.css" -o -name "*.html" | xargs ls -lh
        
  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
  # Monitor website health
  monitor:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Wait for deployment
      run: sleep 30
      
    - name: Check website status
      run: |
        # Extract repository name from GITHUB_REPOSITORY
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        URL="https://${{ github.repository_owner }}.github.io/$REPO_NAME"
        echo "Checking URL: $URL"
        
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL || echo "000")
        if [ "$HTTP_STATUS" = "200" ]; then
          echo "✅ Website is accessible at $URL"
        else
          echo "❌ Website returned HTTP $HTTP_STATUS"
          echo "ℹ️ This might be normal if the site is still deploying"
        fi
        
    - name: Notify on success
      if: success()
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        echo "🎉 Deployment successful!"
        echo "🌐 Website URL: https://${{ github.repository_owner }}.github.io/$REPO_NAME"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "💥 Deployment failed!"
        echo "Please check the logs for more information."